// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASL4W02uMlK-_199XLnBi-3L6j97gkKCU',
    appId: '1:842473856335:web:51ee981cb86ad560fb393a',
    messagingSenderId: '842473856335',
    projectId: 'didirooms-b51af',
    authDomain: 'didirooms-b51af.firebaseapp.com',
    storageBucket: 'didirooms-b51af.appspot.com',
    measurementId: 'G-X48T8XYE7J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiiLdMez-pWvzwi6pFYKfwYns9AUPsIzI',
    appId: '1:842473856335:android:210c9d2f8e2294a6fb393a',
    messagingSenderId: '842473856335',
    projectId: 'didirooms-b51af',
    storageBucket: 'didirooms-b51af.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBq9_rNEvVROdcgDv4tLDiI2beLEbYeYi4',
    appId: '1:842473856335:ios:b2506d209b56bc32fb393a',
    messagingSenderId: '842473856335',
    projectId: 'didirooms-b51af',
    storageBucket: 'didirooms-b51af.appspot.com',
    iosBundleId: 'com.example.didi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBq9_rNEvVROdcgDv4tLDiI2beLEbYeYi4',
    appId: '1:842473856335:ios:b2506d209b56bc32fb393a',
    messagingSenderId: '842473856335',
    projectId: 'didirooms-b51af',
    storageBucket: 'didirooms-b51af.appspot.com',
    iosBundleId: 'com.example.didi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASL4W02uMlK-_199XLnBi-3L6j97gkKCU',
    appId: '1:842473856335:web:39b0125c9d19e02bfb393a',
    messagingSenderId: '842473856335',
    projectId: 'didirooms-b51af',
    authDomain: 'didirooms-b51af.firebaseapp.com',
    storageBucket: 'didirooms-b51af.appspot.com',
    measurementId: 'G-PMG3TSNBKL',
  );
}
